sudo: true
language: python
python:
#- "3.5"
  - "3.6"
before_install:
- ls -la
#cache:
#- pip
install:
- echo 'install'
#- pip install -e collector
#- pip install -e viewer
#- 7z x -oviewer/callspect/static/ viewer/callspect/static/deps.7z
script:
- echo 'script'
#- python collector/tests.py && python viewer/tests.py
deploy:
  skip_cleanup: true
  provider: script
  script: ./_pypi_publish.sh
  script: chmod +x ./_pypi_publish.sh && ./_pypi_publish.sh
  #on:
  #  tags: true
  #  branch: master
