try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


with open('README.md') as ptr:
    long_description = ptr.read()


setup(
    name="callspect",
    description="Inspect program execution from data generated by `callspectpy`",
    long_description=long_description,
    license="MIT",
    version="0.1.0",
    author="xliiv",
    author_email="tymoteusz.jankowski@gmail.com",
    maintainer="xliiv",
    maintainer_email="tymoteusz.jankowski@gmail.com",
    url="https://github.com/xliiv/callspect",
    packages=['callspect'],
    install_requires=[
        'Flask==0.12.2',
    ],
    entry_points={
        'console_scripts': [
            'callspect = callspect_cli:run',
        ],
    },
    classifiers=[
      'Programming Language :: Python :: 3',
    ]
)
